XCOPY "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListMP2\TvWishListMP2\bin\Release\TvWishListMP2.dll" "C:\Program Files (x86)\Team MediaPortal\MP2-Client\Plugins\TvWishListMP2\TvWishListMP2.dll" /S /C /I /Y
XCOPY "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListMPExtendedProvider0.5\TvWishListMPExtendedProvider0.5\bin\Release\TvWishListMPExtendedProvider0.5.dll" "C:\Program Files (x86)\Team MediaPortal\MP2-Client\Plugins\TvWishListMPExtendedProvider0.5\TvWishListMPExtendedProvider0.5.dll" /S /C /I /Y

XCOPY "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListInterface\TvWishListInterface\bin\Release\TvWishListInterface.dll" "C:\Program Files (x86)\Team MediaPortal\MP2-Client\Plugins\TvWishListMPExtendedProvider0.5\TvWishListInterface.dll" /S /C /I /Y
XCOPY "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListInterface\TvWishListInterface\bin\Release\TvWishListInterface.dll" "C:\Program Files (x86)\Team MediaPortal\MP2-Client\Plugins\TvWishListMP2\TvWishListInterface.dll" /S /C /I /Y
XCOPY "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListInterface\TvWishListInterface\bin\Release\TvWishListInterface.dll" "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListMP2\TvWishListMP2\bin\Release\TvWishListInterface.dll" /S /C /I /Y
XCOPY "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListInterface\TvWishListInterface\bin\Release\TvWishListInterface.dll" "H:\User Daten\Visual C# Projects\TvWishList\TvWishListV1.3.0.7 Test Interfaces\TvWishListV1.3.0.7.Source\MP2 TvWishListMP2\TvWishListMPExtendedProvider0.5\TvWishListMPExtendedProvider0.5\bin\Release\TvWishListInterface.dll" /S /C /I /Y


PAUSE